export interface Company {
  id: string;
  name: string;
  createdAt: string;
}

export interface CreateCompanyInput {
  name: string;
}

export interface CompanyRepository {
  list(): Promise<Company[]>;
  get(id: string): Promise<Company | undefined>;
  create(input: CreateCompanyInput): Promise<Company>;
  update(id: string, patch: Partial<Omit<Company, 'id'>>): Promise<Company>;
  remove(id: string): Promise<void>;
}

export type LineRowFormat = 'normal' | 'total' | 'metric';
export type LineNumberFormat = 'number' | 'percentage' | 'multiple';
export type LineSign = 'natural' | 'absolute';
/** How a flow/balance line rolls up when periods are collapsed (e.g. quarters into a year) — 'none' for ratios/metrics that don't aggregate. Not used until period rollup ships. */
export type LineAggregation = 'sum' | 'last' | 'none';

/** A formula resolved at authoring time (see lib/engine/resolve.ts) — every reference is a
 *  specific line id, not a name, so it survives a rename or reorder elsewhere in the schema.
 *  `driverRef` is never hand-typed or parsed from text (unlike every other node here) — it's
 *  only ever constructed directly by the projection-method UI (see DriverDefinition below). */
export type ResolvedFormula =
  | { kind: 'num'; value: number }
  | { kind: 'ref'; lineId: string }
  | { kind: 'driverRef'; driverId: string }
  | { kind: 'neg'; arg: ResolvedFormula }
  | { kind: 'bin'; op: '+' | '-' | '*' | '/' | '^'; left: ResolvedFormula; right: ResolvedFormula }
  | { kind: 'call'; fn: 'sum' | 'min' | 'max' | 'avg' | 'abs' | 'priorPeriod' | 'priorYear'; args: ResolvedFormula[] };

/** How a line's PROJECTED periods derive a value when no mapped source exists for them (an
 *  actual period always prefers its mapped value regardless of this — see StatementLine.formula
 *  and lib/engine/evaluate.ts's computeLine). 'growth'/'percent-of'/'days-of' each generate a
 *  formula that reads a DriverDefinition's per-period value via a driverRef node; 'flat' is a
 *  pure carry-forward (priorPeriod(self)) and needs no driver at all. */
export type ProjectionMethod = 'growth' | 'percent-of' | 'days-of';

/** A named, per-period leaf value (see StatementSchema.drivers) — architecturally almost
 *  identical to a non-calculated line, just living outside the statement sections and feeding
 *  the drivers panel instead of the grid. Referenced from a formula via a driverRef node,
 *  resolved by the same graph/evaluator every other formula uses; not a special calculation
 *  method the engine special-cases. */
export interface DriverDefinition {
  /** Stable once created — never regenerated, since formulas reference it. */
  id: string;
  /** Auto-suggested from the target line at creation (e.g. "Revenue Growth Rate"), editable after. */
  name: string;
  /** Display only ("%", "days") — never read by the engine. */
  unit: string;
  targetLineId: string;
  method: ProjectionMethod;
  /** Required for 'percent-of' | 'days-of' — the line this driver is expressed against. Absent
   *  for 'growth', which references its own target line via priorPeriod instead. */
  basisLineId?: string;
}

export interface StatementLine {
  /** Stable once created — never regenerated on rename/reorder/move, since formulas and aliases reference it. */
  id: string;
  name: string;
  /** Must have an explicit mapped value for every actual period — independent of whether the
   *  line also carries a projection formula for its future periods (see `projection`). */
  required: boolean;
  rowFormat: LineRowFormat;
  numberFormat: LineNumberFormat;
  sign: LineSign;
  aggregation: LineAggregation;
  /** Resolved at authoring time (see lib/engine/resolve.ts) — refs point at a specific line id,
   *  not a name, so a rename or reorder elsewhere in the schema never changes what this reads.
   *  An explicit mapped value always wins over this when one exists for a given period — this is
   *  the fallback, used for any period without one (in practice: every projected period, and any
   *  actual period this line simply isn't mappable/reported for). `null` means no formula at all. */
  formula: ResolvedFormula | null;
  /** Set only when `formula` was generated by the projection-method UI rather than hand-written —
   *  lets the schema editor re-render the right controls, and distinguishes a genuine structural
   *  calculated line (formula set, projection null) from a normally-sourced line with a forward
   *  projection (formula set, projection non-null). 'flat' carries no DriverDefinition (its
   *  formula is a pure `priorPeriod(self)` carry-forward); every other method does. */
  projection: { method: 'flat' } | { method: ProjectionMethod; driverId: string } | null;
  aliases: string[];
}

export interface StatementSection {
  /** Stable once created — never regenerated on rename/reorder. */
  id: string;
  name: string;
  /** Array position is the display order within the section. */
  lines: StatementLine[];
}

export interface StatementSchema {
  /** Stable once created — never regenerated on rename. */
  id: string;
  name: string;
  /** Set when this schema was created via duplicate() — provenance only, no runtime merge with the source. */
  copiedFromSchemaId?: string;
  createdAt: string;
  /** Bumped on every save() — part of a computed result's version stamp (see ComputedResult), so a
   *  formula/driver edit invalidates any cached result for every model built on this schema. */
  updatedAt: string;
  /** Array position is the display order of sections. */
  sections: StatementSection[];
  drivers: DriverDefinition[];
}

export interface StatementSchemaRepository {
  list(): Promise<StatementSchema[]>;
  get(id: string): Promise<StatementSchema | undefined>;
  create(input: { name: string }): Promise<StatementSchema>;
  duplicate(id: string, name: string): Promise<StatementSchema>;
  /** Returns the persisted record (its `updatedAt` is bumped on save) — use this, not the object
   *  passed in, as the new source of truth for any local state tracking the schema. */
  save(schema: StatementSchema): Promise<StatementSchema>;
  remove(id: string): Promise<void>;
}

/** "extract-ai" is a placeholder for now — not selectable until AI extraction exists. */
export type ModelTemplateType = 'basis-template' | 'extract-ai';

/** Pure upload provenance — where a model's historicals came from. Carries no mapping or resolved values itself. */
export interface ModelImport {
  id: string;
  companyId: string;
  templateType: ModelTemplateType;
  /** Which statement schema this import is mapped (or being mapped) against. */
  statementSchemaId: string;
  fileName: string;
  fileSize: number;
  uploadedAt: string;
  /** The raw uploaded workbook, read back to re-parse (e.g. to seed prior-mapping hints for the next import). */
  file: Blob;
}

export interface CreateModelImportInput {
  companyId: string;
  templateType: ModelTemplateType;
  statementSchemaId: string;
  file: File;
}

export interface ModelImportRepository {
  get(id: string): Promise<ModelImport | undefined>;
  create(input: CreateModelImportInput): Promise<ModelImport>;
  remove(id: string): Promise<void>;
}

export type PeriodType = 'FY' | 'Quarter' | 'Semi-Annual';

export interface ParsedPeriod {
  type: PeriodType;
  /** ISO date string for the period end, as read from the source file. */
  date: string;
  /** Display label as given in the file, e.g. "FY 2026". */
  name: string;
}

export interface ParsedSourceLine {
  /** Stable within one parsed workbook (derived from row position at parse time). */
  id: string;
  section: string;
  name: string;
  /** Aligned index-for-index with ParsedWorkbook.periods; null where the cell was blank. */
  values: (number | null)[];
}

export interface ParsedWorkbook {
  periods: ParsedPeriod[];
  lines: ParsedSourceLine[];
}

/** 'prior' is a hit against a name carried from the company's previous mapping — distinct from 'alias' (a registered schema alias), read differently in review. */
export type MatchMethod = 'exact' | 'alias' | 'prior' | 'fuzzy' | 'ai' | 'manual' | 'none';

export interface LineMapping {
  targetLineId: string;
  /** Source line ids being summed into this target. Empty means unmapped. */
  sourceLineIds: string[];
  method: MatchMethod;
  /** 0-1. Meaningless when method is 'none'. */
  confidence: number;
  note: string;
  /** Manually confirmed despite low confidence — suppresses the review flag without changing the match. */
  approved: boolean;
}

/** One mapping record per uploaded file per schema — separate from ModelImport so it can be edited (re-reviewed, corrected) independently of the file it was produced from. */
export interface Mapping {
  id: string;
  modelImportId: string;
  statementSchemaId: string;
  lines: LineMapping[];
  mappedAt: string;
}

export interface CreateMappingInput {
  modelImportId: string;
  statementSchemaId: string;
  lines: LineMapping[];
}

export interface MappingRepository {
  get(id: string): Promise<Mapping | undefined>;
  create(input: CreateMappingInput): Promise<Mapping>;
  /** Updates lines in place — used when re-reviewing the mapping of the *same* uploaded file, not when a new file supersedes it. */
  save(id: string, lines: LineMapping[]): Promise<Mapping>;
}

/** Anticipates phase 04's projected periods; only 'actual' is ever produced before then. */
export type PeriodKind = 'actual' | 'projected';

export interface TimelinePeriod {
  /** Stable across re-parses of the same workbook — derived from type + date, not array position. */
  id: string;
  type: PeriodType;
  /** ISO date string for the period end. */
  endDate: string;
  label: string;
  kind: PeriodKind;
}

export type Timeline = TimelinePeriod[];

/**
 * The one current model for a company — never a peer among several. Re-mapping supersedes it
 * (with a confirm — see ModelMappingScreen); superseded models aren't retained here. Durable
 * point-in-time history is what Snapshot (a later phase) is for.
 */
export interface Model {
  id: string;
  companyId: string;
  name: string;
  statementSchemaId: string;
  modelImportId: string;
  mappingId: string;
  timeline: Timeline;
  /** Resolved once at mapping-save time, index-aligned to `timeline` — never re-derived from the workbook on read. */
  historicals: Record<string, (number | null)[]>;
  /** Per-driver, per-period assumption values — index-aligned to `timeline`, keyed by
   *  DriverDefinition.id from the model's statement schema. Meaningful only at projected-period
   *  indices; edited via the drivers panel, never resolved from a workbook. */
  driverValues: Record<string, (number | null)[]>;
  createdAt: string;
  /** Bumped on every update() — part of a computed result's version stamp (see ComputedResult). */
  updatedAt: string;
}

export interface CreateModelInput {
  companyId: string;
  name: string;
  statementSchemaId: string;
  modelImportId: string;
  mappingId: string;
  timeline: Timeline;
  historicals: Record<string, (number | null)[]>;
}

export interface ModelRepository {
  getForCompany(companyId: string): Promise<Model | undefined>;
  /** Atomic replace: if the company already has a current model, its ModelImport/Mapping/Scenarios are deleted first. Callers confirm with the user before calling this — the repository itself never asks. */
  create(input: CreateModelInput): Promise<Model>;
  update(id: string, patch: Partial<Pick<Model, 'name' | 'timeline' | 'historicals' | 'driverValues'>>): Promise<Model>;
  /** Cascades to the model's ModelImport, Mapping and Scenarios. */
  remove(id: string): Promise<void>;
}

/**
 * A named fork of a model's driver assumptions — same lines and formulas as the model (scenarios
 * never diverge structurally), only `driverValues` differ. `driverValues` is a SPARSE override
 * layer, same shape as `Model.driverValues` and index-aligned to the same `timeline`: a `null` (or
 * an entirely absent driverId/index) means "not overridden here", cascading down to the model's
 * own `driverValues` at that cell (which may itself be explicit or fall further to the engine's
 * computed default — see evaluate.ts's `defaultDriverValue`). There is deliberately no way to say
 * "ignore the model's value here, use the pure computed default instead" — clearing a scenario
 * cell always falls through to the model, never past it. A real but narrow gap (documented, not
 * fixed): a scenario can't revert a single driver to trend while the model still assumes momentum.
 * The implicit "Base case" (the model's own driverValues) is never itself a Scenario row — see
 * lib/scenario.ts's mergeScenarioDriverValues, used to compute an effective driverValues map for
 * evaluateModel without the engine ever needing to know scenarios exist.
 */
export interface Scenario {
  id: string;
  modelId: string;
  name: string;
  driverValues: Record<string, (number | null)[]>;
  createdAt: string;
  /** Bumped on every update() — part of a computed result's version stamp (see ComputedResult). */
  updatedAt: string;
}

export interface CreateScenarioInput {
  modelId: string;
  name: string;
  /** Defaults to `{}` (fully sparse — everything cascades to the model). Duplicating an existing
   *  scenario or the implicit Base case passes a real snapshot here instead. */
  driverValues?: Record<string, (number | null)[]>;
}

export interface ScenarioRepository {
  list(modelId: string): Promise<Scenario[]>;
  get(id: string): Promise<Scenario | undefined>;
  create(input: CreateScenarioInput): Promise<Scenario>;
  update(id: string, patch: Partial<Pick<Scenario, 'name' | 'driverValues'>>): Promise<Scenario>;
  remove(id: string): Promise<void>;
}

/** 'base' sentinel or a real Scenario.id — mirrors ModelWorkspaceScreen's activeScenarioId
 *  convention (the implicit Base case is never itself a stored Scenario row). */
export type ScenarioKey = 'base' | string;

/** The three fields a computed result's freshness depends on — compared against the CURRENT live
 *  `updatedAt` values on read (see lib/computedCache.ts's versionStampMatches). A mismatch means
 *  outputs may no longer agree with the inputs that produced them — the architecture contract's
 *  "calculation desync" — and is always treated as a silent cache miss (recompute, overwrite),
 *  never surfaced as a user-facing staleness badge; that's a different concept (see the modeling
 *  plan's Phase 6 notes on temporal staleness, deliberately not built yet). */
export interface ComputedResultVersionStamp {
  modelUpdatedAt: string;
  /** null when scenarioId is 'base' — Base has no Scenario row to stamp. */
  scenarioUpdatedAt: string | null;
  schemaUpdatedAt: string;
}

/**
 * A materialized, plain-data snapshot of an EvaluationResult (see lib/engine/evaluate.ts) for one
 * (model, scenario) pair — "computed state is a cache, not a source" per the architecture
 * contract. EvaluationResult itself is a set of closures over Maps and can't be persisted directly;
 * `values`/`errors` are the same data flattened to plain records via lib/computedCache.ts's
 * materializeEvaluation, keyed by lineId and index-aligned to the model's timeline.
 */
export interface ComputedResult {
  /** `${modelId}:${scenarioId}` — also the natural primary key, so `set()` is a plain upsert. */
  id: string;
  modelId: string;
  scenarioId: ScenarioKey;
  values: Record<string, (number | null)[]>;
  errors: Record<string, string>;
  versionStamp: ComputedResultVersionStamp;
  computedAt: string;
}

export interface ComputedResultRepository {
  get(modelId: string, scenarioId: ScenarioKey): Promise<ComputedResult | undefined>;
  set(result: ComputedResult): Promise<void>;
}
