import type { LineMapping, ParsedSourceLine, StatementLine, StatementSection } from '../data';
import { isFormulaOnly } from './lineRole';

const FUZZY_THRESHOLD = 0.6;

/**
 * Case/punctuation/whitespace-insensitive form of a line name, shared with the AI importer's evidence scan and the
 * summary-line lookup so all of them agree on what "matches". `%` and `/` are kept as their own tokens because they
 * change what a line is ("% Revenue" is not "Revenue", "EV / EBITDA" is not "EV EBITDA"); every other symbol is noise.
 */
export function normalize(value: string): string {
  return value.trim().toLowerCase().replace(/[%/]/g, ' $& ').replace(/[^a-z0-9%/]+/g, ' ').replace(/\s+/g, ' ').trim();
}

function levenshtein(a: string, b: string): number {
  const rows = a.length + 1;
  const cols = b.length + 1;
  const dp: number[][] = Array.from({ length: rows }, () => new Array(cols).fill(0));
  for (let i = 0; i < rows; i++) dp[i][0] = i;
  for (let j = 0; j < cols; j++) dp[0][j] = j;
  for (let i = 1; i < rows; i++) {
    for (let j = 1; j < cols; j++) {
      dp[i][j] = a[i - 1] === b[j - 1] ? dp[i - 1][j - 1] : 1 + Math.min(dp[i - 1][j - 1], dp[i - 1][j], dp[i][j - 1]);
    }
  }
  return dp[rows - 1][cols - 1];
}

/** 0-1 similarity between two strings, normalized for punctuation/case/whitespace. */
function similarity(a: string, b: string): number {
  const na = normalize(a);
  const nb = normalize(b);
  if (!na || !nb) return 0;
  if (na === nb) return 1;
  const distance = levenshtein(na, nb);
  return 1 - distance / Math.max(na.length, nb.length);
}

function unmapped(targetLineId: string, note: string): LineMapping {
  return { targetLineId, sourceLineIds: [], method: 'none', confidence: 0, note, approved: false };
}

/**
 * Exact -> alias -> fuzzy matching, one target line at a time. Only ever proposes a single
 * source line per target — aggregating multiple source lines into one target is a manual
 * action in the mapping UI, not something this pass guesses at.
 *
 * The AI step from the matching hierarchy isn't implemented: there's no LLM call wired into
 * this app yet. Anything that falls through fuzzy matching comes back unmapped ('none') with
 * a note saying so, rather than faking an AI result.
 */
export function matchStatementLines(
  sections: StatementSection[],
  sourceLines: ParsedSourceLine[],
  additionalAliasesByLineId: Record<string, string[]> = {},
): Record<string, LineMapping> {
  const result: Record<string, LineMapping> = {};

  for (const section of sections) {
    for (const line of section.lines) {
      // A line lib/debtSchedule.ts's regenerateDebtSchedule generates (debtScheduleRole set) is
      // NEVER directly mappable — its value always comes from its own formula. Skipping the
      // match attempt entirely (not just declining to show it) matters here: a coincidental fuzzy
      // match — e.g. the schedule's own "Interest Expense" total against a reported "Net Interest
      // Expense" row — would otherwise be offered as a mapping for a line that has none.
      if (line.debtScheduleRole) {
        result[line.id] = unmapped(line.id, 'Auto-generated by the Debt Schedule — never directly mapped.');
        continue;
      }
      // A Calculated or Check line is never mapped either — its formula is its value in every
      // period. Only a Required/Optional line gets a match attempt.
      if (isFormulaOnly(line)) {
        result[line.id] = unmapped(line.id, 'Calculated — never mapped.');
        continue;
      }
      result[line.id] = matchOne(line, sourceLines, additionalAliasesByLineId[line.id] ?? []);
    }
  }

  return result;
}

/** A hit on `hits`: the first is proposed, any others (the same name under another group) ride along as alternatives to be picked between in review. */
function hit(target: StatementLine, hits: ParsedSourceLine[], method: 'exact' | 'alias' | 'prior', confidence: number, note: (line: ParsedSourceLine) => string): LineMapping {
  const [first, ...rest] = hits;
  return {
    targetLineId: target.id,
    sourceLineIds: [first.id],
    ...(rest.length > 0 ? { alternativeSourceLineIds: rest.map((l) => l.id) } : {}),
    method,
    confidence,
    note: rest.length > 0 ? `${hits.length} lines match — ${note(first)} Pick the right one.` : note(first),
    approved: false,
  };
}

function matchOne(target: StatementLine, sourceLines: ParsedSourceLine[], extraAliases: string[]): LineMapping {
  const targetName = normalize(target.name);

  const exact = sourceLines.filter((source) => normalize(source.name) === targetName);
  if (exact.length > 0) return hit(target, exact, 'exact', 1, (l) => `"${l.name}" matches the line name exactly.`);

  const aliasSet = new Set(target.aliases.map(normalize).filter(Boolean));
  if (aliasSet.size > 0) {
    const aliasHits = sourceLines.filter((source) => aliasSet.has(normalize(source.name)));
    if (aliasHits.length > 0) return hit(target, aliasHits, 'alias', 1, (l) => `"${l.name}" matches a registered alias.`);
  }

  // Names carried from the company's previous mapping — a real hit, but not a registered
  // schema alias, so it's tagged and reviewed differently (see MatchMethod).
  const priorSet = new Set(extraAliases.map(normalize).filter(Boolean));
  if (priorSet.size > 0) {
    const priorHits = sourceLines.filter((source) => priorSet.has(normalize(source.name)));
    if (priorHits.length > 0) return hit(target, priorHits, 'prior', 1, (l) => `"${l.name}" matches the line mapped here last time.`);
  }

  let bestScore = 0;
  let best: ParsedSourceLine[] = [];
  for (const source of sourceLines) {
    const score = similarity(target.name, source.name);
    if (score < FUZZY_THRESHOLD) continue;
    if (score > bestScore) {
      bestScore = score;
      best = [source];
    } else if (score === bestScore) {
      best.push(source);
    }
  }
  if (best.length > 0) {
    const [first, ...rest] = best;
    return {
      targetLineId: target.id,
      sourceLineIds: [first.id],
      ...(rest.length > 0 ? { alternativeSourceLineIds: rest.map((l) => l.id) } : {}),
      method: 'fuzzy',
      confidence: Number(bestScore.toFixed(2)),
      note: `${rest.length > 0 ? `${best.length} lines match — ` : ''}Fuzzy match on "${first.name}" (score ${bestScore.toFixed(2)}).${rest.length > 0 ? ' Pick the right one.' : ''}`,
      approved: false,
    };
  }

  return unmapped(target.id, 'No exact, alias, or fuzzy match above threshold. AI-assisted matching is not yet implemented.');
}
