import { useState } from 'react';
import { Button } from '@basis/design-system';
import type { LineMapping, ParsedSourceLine, ParsedWorkbook, StatementLine } from '../../../data';
import { formatPeriodValue, isAmbiguous, isLowConfidence, MATCH_METHOD_META } from './mappingFormatting';
import { sourceLineLabel } from '../../../lib/sourceLineLabel';
import { SourceLineChecklist } from './SourceLineChecklist';
import { LineSettingsPanel, type LineSettingsSection } from '../../common/LineSettingsPanel';

const METHOD_DESCRIPTIONS: Record<string, string> = {
  exact: 'Exact name match',
  alias: 'Alias dictionary',
  prior: 'Mapped this way last time',
  fuzzy: 'Fuzzy match',
  ai: 'AI proposal',
  manual: 'Manual override',
  none: 'No match',
};

interface MappingRowDetailProps {
  target: StatementLine;
  sectionName: string;
  mapping: LineMapping;
  workbook: ParsedWorkbook;
  onSetSourceLines: (sourceLineIds: string[]) => void;
  onApprove: () => void;
  /** Puts back what this line was mapped to before an AI review changed it. */
  onReject: () => void;
  /** Set once this line has ≥1 real child line (parentLineId pointing here) summing into it —
   *  its value is superseded by that sum for every period (see StatementLine.allowsSubLines' own
   *  doc comment), so direct mapping here would silently be ignored. Disables the checklist
   *  below in favor of an explanation. */
  supersededByInstanceCount?: number;
  /** True when this line is itself generated by lib/debtSchedule.ts's regenerateDebtSchedule
   *  (StatementLine.debtScheduleRole is set) — a tranche's own Beginning/Interest/.../Ending
   *  Balance, or one of the three schedule-level totals. Its value comes entirely from other
   *  generated lines' formulas, so direct mapping is pointless — the checklist is disabled here
   *  too, same outcome as supersededByInstanceCount above though the mechanism differs (no
   *  parentLineId children involved). A line that merely REFERENCES a debt-schedule total by an
   *  ordinary formula (Net Interest Expense, say) is NOT this — it's a ordinary structural
   *  calculated line handled the normal way, never reaching this component with this flag set. */
  calculatedByDebtSchedule?: boolean;
  /** True for a Calculated or Check line (see lib/lineRole.ts) — its formula is its value in every
   *  period, so nothing is mapped to it; the panel is read-only with the formula shown. */
  calculated?: boolean;
  /** Display text for `target.formula` (see lib/engine/resolve.ts's formatFormula) — shown
   *  alongside the calculatedByDebtSchedule explanation so a generated line's own roll-forward
   *  is inspectable without leaving the mapping screen. Omitted (or empty) shows no formula row. */
  formula?: string;
  onClose: () => void;
}

const DEFAULT_OPEN_SECTIONS = ['mapping', 'match'];

/** Mapping-only now — name/projection/structure/debt-tranche editing all live in Edit-schema
 *  mode's shared LineSettingsPanelContent instead (see SectionEditor.tsx). This component's job
 *  is strictly the mapping act: which source line(s) feed this target, and reviewing/approving
 *  the match. */
export function MappingRowDetail({
  target, sectionName, mapping, workbook, onSetSourceLines, onApprove, onReject, supersededByInstanceCount,
  calculatedByDebtSchedule, calculated, formula, onClose,
}: MappingRowDetailProps) {
  const [openKeys, setOpenKeys] = useState<string[]>(DEFAULT_OPEN_SECTIONS);
  const toggleSection = (key: string) => setOpenKeys((prev) => (prev.includes(key) ? prev.filter((k) => k !== key) : [...prev, key]));

  if (supersededByInstanceCount) {
    return (
      <LineSettingsPanel
        title={target.name}
        subtitle="Mapping"
        icon="git-merge"
        onClose={onClose}
        openKeys={openKeys}
        onToggleSection={toggleSection}
        sections={[
          {
            key: 'mapping',
            label: 'Mapping',
            content: (
              <div style={{ fontSize: 'var(--text-xs)', color: 'var(--text-secondary)' }}>
                {target.name} is broken into {supersededByInstanceCount} sub-line{supersededByInstanceCount > 1 ? 's' : ''} — its
                value is the sum of those for every period, so direct mapping here is disabled. Manage its sub-lines from
                Edit schema mode.
              </div>
            ),
          },
        ]}
      />
    );
  }
  if (calculatedByDebtSchedule || calculated) {
    return (
      <LineSettingsPanel
        title={target.name}
        subtitle="Mapping"
        icon="git-merge"
        onClose={onClose}
        openKeys={openKeys}
        onToggleSection={toggleSection}
        sections={[
          {
            key: 'mapping',
            label: 'Mapping',
            content: (
              <div>
                <p style={{ margin: 0, fontSize: 'var(--text-xs)', color: 'var(--text-secondary)' }}>
                  {calculatedByDebtSchedule
                    ? `${target.name} is generated by the Debt Schedule, from the tranche details entered in Edit schema mode — read only here.`
                    : `${target.name} is a calculated line — its formula gives its value in every period, so nothing is mapped to it. Change its type in Edit schema mode.`}
                </p>
                {formula ? (
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-2)', marginTop: 'var(--space-5)' }}>
                    <span style={{ fontSize: 'var(--text-2xs)', fontWeight: 'var(--weight-semibold)', letterSpacing: 'var(--tracking-caps)', textTransform: 'uppercase', color: 'var(--text-secondary)' }}>
                      Formula
                    </span>
                    <span style={{ fontFamily: 'var(--font-mono)', fontSize: 'var(--text-xs)', color: 'var(--text-tertiary)' }}>{formula}</span>
                  </div>
                ) : null}
              </div>
            ),
          },
        ]}
      />
    );
  }

  const sourceById = (id: string): ParsedSourceLine | undefined => workbook.lines.find((line) => line.id === id);
  const methodMeta = MATCH_METHOD_META[mapping.method];
  const showApprove = isLowConfidence(mapping) || isAmbiguous(mapping);
  const candidates = isAmbiguous(mapping)
    ? [...mapping.sourceLineIds, ...(mapping.alternativeSourceLineIds ?? [])].map(sourceById).filter((l): l is ParsedSourceLine => !!l)
    : [];
  const lastPeriodIndex = workbook.periods.length - 1;

  const sections: LineSettingsSection[] = [
    ...(candidates.length > 0
      ? [{
          key: 'candidates',
          label: 'Multiple matches',
          summary: `${candidates.length} lines`,
          content: (
            <div>
              <p style={{ margin: '0 0 var(--space-4)', fontSize: 'var(--text-xs)', color: 'var(--text-secondary)' }}>
                {candidates.length} lines in the file match {target.name} equally well. Choose the one that belongs here.
              </p>
              {candidates.map((line) => (
                <div key={line.id} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 'var(--space-6)', padding: 'var(--space-3) 0', borderBottom: '1px solid var(--border-subtle)' }}>
                  <div style={{ minWidth: 0 }}>
                    <div style={{ fontSize: 'var(--text-sm)', color: 'var(--text-primary)' }}>{line.name}</div>
                    <div style={{ fontSize: 'var(--text-2xs)', color: 'var(--text-tertiary)' }}>
                      {[line.group, line.section, formatPeriodValue(line.values[lastPeriodIndex] ?? null)].filter(Boolean).join(' · ')}
                    </div>
                  </div>
                  <Button size="sm" variant="secondary" onClick={() => onSetSourceLines([line.id])}>Use this</Button>
                </div>
              ))}
            </div>
          ),
        } satisfies LineSettingsSection]
      : []),
    {
      key: 'mapping',
      label: 'Source mapping',
      content: (
        <SourceLineChecklist
          title={`Map ${target.name} from`}
          sectionName={sectionName}
          workbook={workbook}
          sourceLineIds={mapping.sourceLineIds}
          onSetSourceLines={onSetSourceLines}
        />
      ),
    },
    {
      key: 'match',
      label: 'Match details',
      summary: methodMeta.label,
      content: (
        <div>
          {[
            ['Method', METHOD_DESCRIPTIONS[mapping.method]],
            ['Confidence', mapping.method === 'none' ? '—' : mapping.confidence.toFixed(2)],
            ['Source lines', mapping.sourceLineIds.length ? mapping.sourceLineIds.map((id) => { const l = sourceById(id); return l ? sourceLineLabel(l) : ''; }).join(', ') : '—'],
            ['Aggregation', mapping.sourceLineIds.length > 1 ? `Sum of ${mapping.sourceLineIds.length} lines` : mapping.sourceLineIds.length ? 'One-to-one' : '—'],
          ].map(([label, value]) => (
            <div key={label} style={{ display: 'flex', justifyContent: 'space-between', gap: 'var(--space-6)', padding: 'var(--space-2) 0' }}>
              <span style={{ fontSize: 'var(--text-xs)', color: 'var(--text-secondary)' }}>{label}</span>
              <span style={{ fontSize: 'var(--text-xs)', fontFamily: 'var(--font-mono)', color: 'var(--text-body)', textAlign: 'right' }}>{value}</span>
            </div>
          ))}
          <p style={{ margin: 'var(--space-5) 0 0', fontSize: 'var(--text-sm)', fontFamily: 'var(--font-serif)', color: 'var(--text-body)' }}>{mapping.note}</p>

          {mapping.method === 'ai' && !mapping.approved && mapping.previous ? (
            <div style={{ marginTop: 'var(--space-5)' }}>
              <Button size="sm" variant="secondary" iconLeft="undo-2" onClick={onReject}>
                Reject suggestion
              </Button>
              <p style={{ margin: 'var(--space-3) 0 0', fontSize: 'var(--text-2xs)', color: 'var(--text-tertiary)' }}>
                Restores the earlier match{mapping.previous.sourceLineIds.length ? ` (${mapping.previous.method})` : ' — this line was unmapped'}.
              </p>
            </div>
          ) : null}

          {showApprove ? (
            <div style={{ marginTop: 'var(--space-5)' }}>
              <Button size="sm" variant="secondary" iconLeft="check" onClick={onApprove}>
                Approve match
              </Button>
              <p style={{ margin: 'var(--space-3) 0 0', fontSize: 'var(--text-2xs)', color: 'var(--text-tertiary)' }}>
                Confirms {methodMeta.label.toLowerCase()} match {mapping.confidence.toFixed(2)} without changing the source lines.
              </p>
            </div>
          ) : null}
        </div>
      ),
    },
  ];

  return (
    <LineSettingsPanel
      title={target.name}
      subtitle="Mapping"
      icon="git-merge"
      onClose={onClose}
      openKeys={openKeys}
      onToggleSection={toggleSection}
      sections={sections}
    />
  );
}
